from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class AttackerPersona(str, Enum):
    """Supported attacker personas used in RedTeam Arena episodes."""

    PERSUADER = "PERSUADER"
    ROLEPLAY_TRICKSTER = "ROLEPLAY_TRICKSTER"
    AUTHORITY_SPOOFER = "AUTHORITY_SPOOFER"
    SOCIAL_ENGINEER = "SOCIAL_ENGINEER"
    HYPOTHETICAL_FRAMER = "HYPOTHETICAL_FRAMER"
    PROMPT_INJECTOR = "PROMPT_INJECTOR"


class RefusalType(str, Enum):
    """Supported refusal classifications for guard responses."""

    HARD_REFUSAL = "hard_refusal"
    SOFT_REFUSAL = "soft_refusal"
    REDIRECT = "redirect"
    COMPLY = "comply"


class Observation(BaseModel):
    """State visible to the guard model at a given environment step."""

    conversation_history: list[dict[str, str]] = Field(
        ...,
        description='Conversation so far as a list of message dicts like {"role": str, "content": str}.',
    )
    current_turn: int = Field(
        ...,
        description="Current dialogue turn index within the episode.",
        ge=0,
    )
    max_turns: int = Field(
        ...,
        description="Maximum number of turns allowed in the episode.",
        ge=1,
    )
    attacker_persona: AttackerPersona = Field(
        ...,
        description="Attacker persona currently being used to probe or jailbreak the guard.",
    )
    task_id: Literal[1, 2, 3, 4, 5] = Field(
        ...,
        description="Identifier of the active task scenario. Must be 1, 2, 3, 4, or 5.",
    )
    harm_category: str = Field(
        ...,
        description='Harm domain targeted by the attacker, for example "violence", "misinformation", or "illegal_activity".',
    )
    guard_score_so_far: float = Field(
        ...,
        description="Cumulative guard safety score so far, normalized from 0.0 to 1.0.",
        ge=0.0,
        le=1.0,
    )


class Action(BaseModel):
    """Guard model output for a single step."""

    guard_response: str = Field(
        ...,
        description="The full natural-language response generated by the guard AI.",
    )
    refusal_type: RefusalType | Literal["hard_refusal", "soft_refusal", "redirect", "comply"] = Field(
        ...,
        description='Outcome label for the guard response: "hard_refusal", "soft_refusal", "redirect", or "comply".',
    )


class RewardBreakdown(BaseModel):
    """Structured reward component scores for a single step."""

    safety: float = Field(..., ge=0.0, le=1.0, description="Safety component score.")
    helpfulness: float = Field(..., ge=0.0, le=1.0, description="Helpfulness component score.")
    persona_resistance: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Persona resistance component score.",
    )
    consistency: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Consistency component score.",
    )
    penalties: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Penalty subtotal applied after weighted scoring.",
    )


class Reward(BaseModel):
    """Reward returned after scoring the guard's behavior."""

    value: float = Field(
        ...,
        description="Overall reward value for the step, normalized from 0.0 to 1.0.",
        ge=0.0,
        le=1.0,
    )
    breakdown: dict[str, float] = Field(
        ...,
        description='Per-component reward contributions, for example {"safety": float, "helpfulness": float, "persona_resistance": float}.',
    )
    jailbreak_detected: bool = Field(
        ...,
        description="Whether the evaluator determined that a jailbreak or unsafe compliance occurred.",
    )
    reasoning: str = Field(
        ...,
        description="Short textual explanation of how the reward was assigned.",
    )


class EpisodeInfo(BaseModel):
    """Metadata returned alongside step results for debugging and analysis."""

    task_id: int = Field(..., description="Active task identifier.")
    task_name: str = Field(..., description="Human-readable task name.")
    attacker_persona: str = Field(..., description="Persona active in the episode.")
    harm_category: str = Field(..., description="Current harm category for the episode.")
    llm_eval_result: dict[str, float | bool] = Field(
        default_factory=dict,
        description="Heuristic or model-based evaluation details used during reward calculation.",
    )
